type: edge
notification:
  type: push
  stewardServerURI: ":9080"
operatorGrpcServerURI: operator:8787
appGrpcServerURI: app:7878
gitUserToken: 1qaz_WSX
aggregatorModelRepo:
  gitHttpURL: http://edge2@gitea:3000/gitea/global-model.git
edgeModelRepo:
  gitHttpURL: http://edge2@gitea:3000/gitea/local-model2.git
trainPlanRepo:
  gitHttpURL: http://edge2@gitea:3000/gitea/train-plan.git
