# Aggregator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: operator
        image: <registry>/harmonia/operator
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          name: steward
        volumeMounts:
        - name: config
          mountPath: /app/config.yml
          subPath: aggregator-config.yml
        - name: shared-repos
          mountPath: /repos
      - name: application
        image: <registry>:mnist_agg
        imagePullPolicy: Always
        volumeMounts:
        - name: shared-repos
          mountPath: /repos
      volumes:
      - name: config
        configMap:
          name: aggregator-config
      - name: shared-repos
        emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: mnist-aggregator
spec:
  selector:
    app: aggregator
  ports:
  - name: aggregator
    port: 9080
    targetPort: 9080
  type: NodePort

---
# Edge1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge1
  labels:
    app: edge1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge1
  template:
    metadata:
      labels:
        app: edge1
    spec:
      containers:
      - name: operator
        image: <registry>/harmonia/operator
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          name: steward
        volumeMounts:
        - name: config
          mountPath: /app/config.yml
          subPath: edge-config.yml
        - name: shared-repos
          mountPath: /repos
      - name: application
        image: <registry>/mnist_edge
        imagePullPolicy: Always
        volumeMounts:
        - name: shared-repos
          mountPath: /repos
      volumes:
      - name: config
        configMap:
          name: edge1-config
      - name: shared-repos
        emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: mnist-edge1
spec:
  selector:
    app: edge1
  ports:
  - name: edge1
    port: 9080
    targetPort: 9080
  type: NodePort

---
# Edge2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge2
  labels:
    app: edge2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge2
  template:
    metadata:
      labels:
        app: edge2
    spec:
      containers:
      - name: operator
        image: <registry>/harmonia/operator
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          name: steward
        volumeMounts:
        - name: config
          mountPath: /app/config.yml
          subPath: edge-config.yml
        - name: shared-repos
          mountPath: /repos
      - name: application
        image: <registry>/mnist_edge
        imagePullPolicy: Always
        volumeMounts:
        - name: shared-repos
          mountPath: /repos
      volumes:
      - name: config
        configMap:
          name: edge2-config
      - name: shared-repos
        emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: mnist-edge2
spec:
  selector:
    app: edge2
  ports:
  - name: edge2
    port: 9080
    targetPort: 9080
  type: NodePort
